default: &default

  adapter: postgresql
  encoding: unicode
  pool: 5

  host: localhost
  username: tic_tac_toe
  password: <%= ENV['TIC_TAC_TOE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: tic_tac_toe_development
  username: tic_tac_toe
  password: <%= ENV['TIC_TAC_TOE_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: tic_tac_toe_test
  username: tic_tac_toe
  password: <%= ENV['TIC_TAC_TOE_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: tic_tac_toe_production
  username: tic_tac_toe
  password: <%= ENV['TIC_TAC_TOE_DATABASE_PASSWORD'] %>
